# Vectors

See pytorch's DOCUMENTATION about Vectors: https://pytorch.org/tutorials/beginner/basics/tensor_tutorial.html

Tensors store data points in different dimensions (similar to matrices). You can create, and perform maths with them. Usually they hold values for Neural Networks (input data, but also during processing).

Create Tensors:
- hardcode values
- `torch.Tensor(d1,d2,...)`
- `torch.randn(d1,d2,...)`

Size:
- `x.size()`


Calculation:
- `torch.add(x1,x2)`

In [15]:
import torch

### Creating Tensors

In [11]:
# Method: hardcode Tensor
x0 = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])
x0

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [7]:
# Method: torch.Tensor to create 5 x 1 tensor (vector)
x1 = torch.Tensor(5)  
x1

tensor([1.0286e-38, 9.0919e-39, 9.3674e-39, 9.2755e-39, 1.4013e-43])

In [8]:
# Method: torch.Tensor to create  5 x 3 tensor (matrix)
x2 = torch.Tensor(5,3)  
x2

tensor([[7.7078e+04, 3.8956e-43, 7.7078e+04],
        [3.8956e-43, 7.7078e+04, 3.8956e-43],
        [7.7078e+04, 3.8956e-43, 7.7078e+04],
        [3.8956e-43, 7.7078e+04, 3.8956e-43],
        [7.7078e+04, 3.8956e-43, 7.7078e+04]])

In [9]:
# # Method: torch.randn() to create random tensor
x3 = torch.randn(4,2)
x3

tensor([[-0.3346, -0.9669],
        [ 1.3559,  0.2820],
        [-0.2368,  0.4859],
        [-1.7264, -0.9102]])

### Size of Tensors

In [10]:
x3.size()

torch.Size([4, 2])

### Maths with Tensors

In [14]:
x4 = torch.Tensor([
    [1,1,1],
    [1,1,1]
])

x5 = torch.Tensor([
    [1,-1,1],
    [-1,1,10]
])

torch.add(x4,x5)

tensor([[ 2.,  0.,  2.],
        [ 0.,  2., 11.]])